M48
; DRILL file {KiCad 7.0.8} date Mon Sep 16 20:38:48 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-16T20:38:48+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0374
%
G90
G05
T1
X1.475Y0.305
X1.475Y0.205
X1.475Y0.105
T2
X0.3758Y0.3024
X0.3758Y0.2039
X0.3758Y0.1055
T0
M30
