M48
; DRILL file {KiCad 7.0.8} date Mon Sep 16 20:57:31 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-16T20:57:31+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0374
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X1.475Y0.305
X1.475Y0.205
X1.475Y0.105
T2
X0.3758Y0.2969
X0.3758Y0.1984
X0.3758Y0.1
T3
X0.8Y0.2
T0
M30
