M48
; DRILL file {KiCad 8.0.5} date 2024-09-29T16:31:31+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-29T16:31:31+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X2.075Y-4.091
X2.075Y-6.375
X4.004Y-4.092
X4.004Y-6.375
T2
X2.35Y-3.0425
M30
